<a href="https://colab.research.google.com/github/prathampharmaai/Pratham-/blob/main/day__6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import info
import pandas as pd
df = pd.read_csv('csv.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      247 non-null    int64
 1   smiles  247 non-null    object
 2   lgK     247 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 5.9+ KB

In [ ]:
df.columns

Index(['id', 'smiles', 'lgK'], dtype='object')

In [ ]:
df[['smiles', 'id']]

                           smiles   id
0                  CC(C)(O)C(=O)O    0
1                CCC(O)(CC)C(=O)O    1
2                O=C(O)C1(O)CCCC1    2
3               O=C(O)C1(O)CCCCC1    3
4              O=C(O)C(O)c1ccccc1    4
..                            ...  ...
242  O=C(O)c1cccc([N+](=O)[O-])c1  244
243                  CCC(O)C(=O)O  245
244                 CCCC(O)C(=O)O  246
245               CC(C)C(O)C(=O)O  247
246            CC(C)(C)C(O)C(=O)O  248

[247 rows x 2 columns]

In [ ]:
df.fillna({"id":1},inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      247 non-null    int64
 1   smiles  247 non-null    object
 2   lgK     247 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 5.9+ KB

In [5]:
import pandas as pd
Url = 'https://raw.githubusercontent.com/dataprofessor/data/master/delaney_solubility_with_descriptors.csv'
df = pd.read_csv(Url)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MolLogP             1144 non-null   float64
 1   MolWt               1144 non-null   float64
 2   NumRotatableBonds   1144 non-null   float64
 3   AromaticProportion  1144 non-null   float64
 4   logS                1144 non-null   float64
dtypes: float64(5)
memory usage: 44.8 KB

In [ ]:
df.shape

(1144, 5)

In [ ]:
df.head(5)
df.dtypes

MolLogP               float64
MolWt                 float64
NumRotatableBonds     float64
AromaticProportion    float64
logS                  float64
dtype: object

In [ ]:
df['MolWt'].max()
df.loc[df['logS'].idxmin()]
df[df['MolLogP']>3]

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion   logS
8     4.30020  215.894                0.0            0.600000 -4.570
10    4.30020  215.894                0.0            0.600000 -4.630
11    3.64680  181.449                0.0            0.666667 -4.000
13    4.73660  393.698                0.0            0.600000 -6.980
14    4.30020  215.894                0.0            0.600000 -5.560
...       ...      ...                ...                 ...    ...
1126  6.25676  368.369                6.0            0.692308 -6.010
1130  4.14820  335.282                7.0            0.260870 -5.680
1133  5.14620  228.294                0.0            1.000000 -6.726
1140  3.42130  286.114                2.0            0.333333 -4.925
1141  3.60960  308.333                4.0            0.695652 -3.893

[370 rows x 5 columns]

In [8]:
import pandas as pd
import numpy as np
Url = 'https://raw.githubusercontent.com/dataprofessor/data/master/delaney_solubility_with_descriptors.csv'
df = pd.read_csv(Url)
df.loc[10,'Molwt'] = np.nan
df.loc[50,'Molwt'] = np.nan
df.loc[100,'logS'] = np.nan

df.isnull().sum()
df['Molwt']=df['MolWt'].fillna(df['MolWt'].mean())
df.dropna(subset=['logS'])

      MolLogP    MolWt  NumRotatableBonds  AromaticProportion   logS    Molwt
0     2.59540  167.850                0.0            0.000000 -2.180  167.850
1     2.37650  133.405                0.0            0.000000 -2.000  133.405
2     2.59380  167.850                1.0            0.000000 -1.740  167.850
3     2.02890  133.405                1.0            0.000000 -1.480  133.405
4     2.91890  187.375                1.0            0.000000 -3.040  187.375
...       ...      ...                ...                 ...    ...      ...
1139  1.98820  287.343                8.0            0.000000  1.144  287.343
1140  3.42130  286.114                2.0            0.333333 -4.925  286.114
1141  3.60960  308.333                4.0            0.695652 -3.893  308.333
1142  2.56214  354.815                3.0            0.521739 -3.790  354.815
1143  2.02164  179.219                1.0            0.461538 -2.581  179.219

[1143 rows x 6 columns]