<a href="https://colab.research.google.com/github/prathampharmaai/Pratham-/blob/main/day_2_row_%26_column.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://raw.githubusercontent.com/dataprofessor/data/master/delaney.csv -O solubility.csv

import pandas as pd
df = pd.read_csv('solubility.csv')

df.columns

--2026-03-14 04:20:00--  https://raw.githubusercontent.com/dataprofessor/data/master/delaney.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58889 (58K) [text/plain]
Saving to: ‘solubility.csv’

solubility.csv      100%[===================>]  57.51K  --.-KB/s    in 0.02s

2026-03-14 04:20:01 (2.93 MB/s) - ‘solubility.csv’ saved [58889/58889]

Index(['Compound ID', 'measured log(solubility:mol/L)',
       'ESOL predicted log(solubility:mol/L)', 'SMILES'],
      dtype='object')

In [2]:
df['Compound ID']

0            1,1,1,2-Tetrachloroethane
1                1,1,1-Trichloroethane
2            1,1,2,2-Tetrachloroethane
3                1,1,2-Trichloroethane
4       1,1,2-Trichlorotrifluoroethane
                     ...
1139                       vamidothion
1140                       Vinclozolin
1141                          Warfarin
1142                          Xipamide
1143                               XMC
Name: Compound ID, Length: 1144, dtype: object

In [4]:
df[['Compound ID','measured log(solubility:mol/L)']]

                         Compound ID  measured log(solubility:mol/L)
0          1,1,1,2-Tetrachloroethane                          -2.180
1              1,1,1-Trichloroethane                          -2.000
2          1,1,2,2-Tetrachloroethane                          -1.740
3              1,1,2-Trichloroethane                          -1.480
4     1,1,2-Trichlorotrifluoroethane                          -3.040
...                              ...                             ...
1139                     vamidothion                           1.144
1140                     Vinclozolin                          -4.925
1141                        Warfarin                          -3.893
1142                        Xipamide                          -3.790
1143                             XMC                          -2.581

[1144 rows x 2 columns]

In [5]:
len(df['Compound ID'])

1144

In [6]:
df.iloc[10]

Compound ID                             1,2,3,5-Tetrachlorobenzene
measured log(solubility:mol/L)                               -4.63
ESOL predicted log(solubility:mol/L)                        -4.621
SMILES                                      Clc1cc(Cl)c(Cl)c(Cl)c1
Name: 10, dtype: object