<a href="https://colab.research.google.com/github/prathampharmaai/Pratham-/blob/main/full_pipeline_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import lazypredict
from lazypredict.Supervised import LazyRegressor
from rdkit.Chem import Descriptors, Crippen, AllChem as Chem
from rdkit import DataStructs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('drug_descriptors.csv')
df

          Name      MW  LogP  hbd  hba  nor  noar  lipinski
0      Aspirin  180.16  1.31    1    3    1     1      True
1  Paracetamol  151.16  1.35    2    2    1     1      True
2    Ibuprofen  206.28  3.07    1    1    1     1      True
3     Atenolol  266.34  0.45    3    4    1     1      True
4    Metformin  129.17 -1.03    4    2    0     0      True
5     Caffeine  194.19 -1.03    0    3    2     2      True

In [7]:
from sklearn.model_selection import train_test_split

X = df[['MW', 'hbd', 'hba', 'nor', 'noar']]
y = df['LogP']

x_train, x_test, y_train, y_test = train_test_split (X, y, test_size = 0.2,random_state=42)

print('Train size:', len(x_train))
print('Test size:', len(x_test))

from sklearn.ensemble import RandomForestRegressor
import numpy as np
np.random.seed(42)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)
r2 = model.score(x_test, y_test)
print('R2 score:', r2)

y_pred = model.predict(x_test)

Train size: 4
Test size: 2
R2 score: -3452.1668999999947

In [9]:
dif= LazyRegressor(verbose=0,ignore_warnings=True,custom_metric=None)
models,predictions=dif.fit(x_train,x_test,y_train,y_test)

models

,Adjusted R-Squared,R-Squared,RMSE,Time Taken
Model,,,,
AdaBoostRegressor,3482.250000,-13924.000000,2.360085,0.048829
DecisionTreeRegressor,3482.250000,-13924.000000,2.360085,0.015004
GradientBoostingRegressor,3482.140694,-13923.562776,2.360048,0.157511
XGBRegressor,3480.654583,-13917.618334,2.359544,0.092396
Lars,3095.597644,-12377.390577,2.225164,0.019316
LinearSVR,2968.820028,-11870.280113,2.179108,0.017055
HuberRegressor,2718.735941,-10869.943763,2.085276,0.183497
TransformedTargetRegressor,2718.735925,-10869.943700,2.085276,0.016955
LinearRegression,2718.735925,-10869.943700,2.085276,0.016234
KernelRidge,2494.182580,-9971.730322,1.997271,0.023797
PassiveAggressiveRegressor,2488.189164,-9947.756657,1.994869,0.013527
SGDRegressor,1754.211138,-7011.844552,1.674855,0.015002
Ridge,1666.324666,-6660.298665,1.632336,0.015435
RandomForestRegressor,1264.440912,-5052.763650,1.421797,0.222718
ExtraTreeRegressor,1222.125000,-4883.500000,1.397784,0.030591
SVR,1208.563286,-4829.253143,1.390000,0.015163
TweedieRegressor,979.578663,-3913.314653,1.251290,0.020383
ElasticNet,798.806204,-3190.224815,1.129819,0.033302
RidgeCV,747.353480,-2984.413921,1.092779,0.014283
OrthogonalMatchingPursuit,669.971250,-2674.885000,1.034579,0.016219
BayesianRidge,583.646236,-2329.584945,0.965523,0.017582
LGBMRegressor,583.265631,-2328.062526,0.965207,0.044575
Lasso,583.265625,-2328.062500,0.965207,0.025179
DummyRegressor,583.265625,-2328.062500,0.965207,0.020242
HistGradientBoostingRegressor,583.265625,-2328.062500,0.965207,0.033761
LassoLars,583.265625,-2328.062500,0.965207,0.014412
QuantileRegressor,485.250000,-1936.000000,0.880227,0.018094
MLPRegressor,478.054374,-1907.217497,0.873663,0.102983
NuSVR,346.253048,-1380.012190,0.743239,0.016930
GaussianProcessRegressor,326.297143,-1300.188572,0.721440,0.019934
BaggingRegressor,279.916250,-1114.665000,0.668031,0.048021
ExtraTreesRegressor,250.780050,-998.120200,0.632177,0.253589