<a href="https://colab.research.google.com/github/prathampharmaai/Pratham-/blob/main/pandas_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://raw.githubusercontent.com/dataprofessor/data/master/delaney.csv -O solubility.csv

import pandas as pd
df = pd.read_csv('solubility.csv')
df.head()

--2026-03-14 04:06:34--  https://raw.githubusercontent.com/dataprofessor/data/master/delaney.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58889 (58K) [text/plain]
Saving to: ‘solubility.csv’

solubility.csv      100%[===================>]  57.51K  --.-KB/s    in 0.02s

2026-03-14 04:06:35 (3.33 MB/s) - ‘solubility.csv’ saved [58889/58889]

,Compound ID,measured log(solubility:mol/L),ESOL predicted log(solubility:mol/L),SMILES
0,"1,1,1,2-Tetrachloroethane",-2.18,-2.794,ClCC(Cl)(Cl)Cl
1,"1,1,1-Trichloroethane",-2.00,-2.232,CC(Cl)(Cl)Cl
2,"1,1,2,2-Tetrachloroethane",-1.74,-2.549,ClC(Cl)C(Cl)Cl
3,"1,1,2-Trichloroethane",-1.48,-1.961,ClCC(Cl)Cl
4,"1,1,2-Trichlorotrifluoroethane",-3.04,-3.077,FC(F)(Cl)C(F)(Cl)Cl

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 4 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Compound ID                           1144 non-null   object
 1   measured log(solubility:mol/L)        1144 non-null   float64
 2   ESOL predicted log(solubility:mol/L)  1144 non-null   float64
 3   SMILES                                1144 non-null   object
dtypes: float64(2), object(2)
memory usage: 35.9+ KB

In [4]:
df.describe()

       measured log(solubility:mol/L)  ESOL predicted log(solubility:mol/L)
count                     1144.000000                           1144.000000
mean                        -3.057997                             -2.994776
std                          2.096502                              1.686520
min                        -11.600000                             -9.702000
25%                         -4.332250                             -3.962250
50%                         -2.870500                             -2.889000
75%                         -1.600000                             -1.846750
max                          1.580000                              1.091000

In [5]:
df.columns

Index(['Compound ID', 'measured log(solubility:mol/L)',
       'ESOL predicted log(solubility:mol/L)', 'SMILES'],
      dtype='object')

In [6]:
df.index

RangeIndex(start=0, stop=1144, step=1)

In [2]:
df.tail()

,Compound ID,measured log(solubility:mol/L),ESOL predicted log(solubility:mol/L),SMILES
1139,vamidothion,1.144,-1.446,CNC(=O)C(C)SCCSP(=O)(OC)(OC)
1140,Vinclozolin,-4.925,-4.377,CC1(OC(=O)N(C1=O)c2cc(Cl)cc(Cl)c2)C=C
1141,Warfarin,-3.893,-3.913,CC(=O)CC(c1ccccc1)c3c(O)c2ccccc2oc3=O
1142,Xipamide,-3.790,-3.642,Cc1cccc(C)c1NC(=O)c2cc(c(Cl)cc2O)S(N)(=O)=O
1143,XMC,-2.581,-2.688,CNC(=O)Oc1cc(C)cc(C)c1